spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/locadmin?useUnicode=true&characterEncoding=utf8
    username: root
    password:
    name: ${spring.application.name}
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      min-idle: 10
      max-active: 50
      max-wait: 10000
      test-on-borrow: true
      validation-query: SELECT 'x';
      test-while-idle: true
  jpa:
    show-sql: true